services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - .:/app:cached
    ports:
      - '8001:8000'
    environment:
      - NODE_ENV=production
      - ADMIN_MYSQL_HOST=${ADMIN_MYSQL_HOST}
      - ADMIN_MYSQL_DATABASE=${ADMIN_MYSQL_DATABASE}
      - ADMIN_MYSQL_USER=${ADMIN_MYSQL_USER}
      - ADMIN_MYSQL_PASSWORD=${ADMIN_MYSQL_PASSWORD}
      - CLIENT_DB_TEMPLATE=${CLIENT_DB_TEMPLATE}
      - JWT_SECRET=${JWT_SECRET}
