services:
  app:
    image: ghcr.io/matheusrodacki/micro_saas_nest_api:main
    ports:
      - '8001:8000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - MYSQL_PORT=${MYSQL_PORT}
      - ADMIN_MYSQL_HOST=${ADMIN_MYSQL_HOST}
      - ADMIN_MYSQL_DATABASE=${ADMIN_MYSQL_DATABASE}
      - ADMIN_MYSQL_USER=${ADMIN_MYSQL_USER}
      - ADMIN_MYSQL_PASSWORD=${ADMIN_MYSQL_PASSWORD}
      - CLIENT_DB_TEMPLATE=${CLIENT_DB_TEMPLATE}
      - JWT_SECRET=${JWT_SECRET}
