FROM node:23

# Defina as variáveis de ambiente
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

# Defina o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto
COPY . .

# Instala as dependências do projeto
RUN npm install 

# Compila o projeto
RUN npm build

# Define o comando padrão
CMD ["npm", "start:prod"]
