services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/micro_saas_nest_api:cached
    command: 'sleep infinity'
    ports:
      - '8000:8000'
    # env_file:
    #   - ../.env
    environment:
      - ADMIN_MYSQL_HOST=${ADMIN_MYSQL_HOST:-mysql}
      - MYSQL_PORT=3306
      - ADMIN_MYSQL_DATABASE=${ADMIN_MYSQL_DATABASE:-db_admin}
      - ADMIN_MYSQL_USER=${ADMIN_MYSQL_USER:-root}
      - ADMIN_MYSQL_PASSWORD=${ADMIN_MYSQL_PASSWORD:-dbpassword}
      - CLIENT_DB_TEMPLATE=${CLIENT_DB_TEMPLATE:-db_client_template}
      - NODE_ENV=${NODE_ENV:-development}
      - JWT_SECRET=${JWT_SECRET:-_jwt_secret}
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ADMIN_MYSQL_PASSWORD:-dbpassword}
      - MYSQL_DATABASE=${ADMIN_MYSQL_DATABASE:-db_admin}
      - MYSQL_USER=${ADMIN_MYSQL_USER:-user_admin}
      - MYSQL_PASSWORD=${ADMIN_MYSQL_PASSWORD:-dbpassword}
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
