version: '3.7'

services:
  app:
    image: node:23
    volumes:
      - ..:/workspaces:cached
    command: "sh -c 'export $(cat /workspaces/.env | xargs) && sleep infinity'"
    ports:
      - '8000:8000'
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=haru_db_v
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: haru_db_v
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
